* Goolge Takout Upload

This script allows to import email archive (/mbox/ file) produced by
[[https://takeout.google.com/settings/takeout][Google Takeout]] into another GMail account. While it is using IMAP
protocol for import, unlike other scripts like [[https://imapsync.lamiral.info/][imapsync]] it uses GMail
IMAP extensions to preserve message labels.

Run without any flags to see usage information. See
/takeoutupload-example.cfg/ file for sample config.

It is written as learning exercise in Haskell Pipes library. It can
process maiboxes of arbitrary size in fixed memory footprint. In case
of error, run with /-d/ commad line option to see IMAP session
transcript.

* References
  - [[https://developers.google.com/gmail/imap/imap-extensions#access_to_gmail_labels_x-gm-labels][GMail IMAP extensions]]
  - [[https://imapsync.lamiral.info/FAQ.d/FAQ.Gmail.txt][Note]] on GMail throttling 
* Implementation
  - Uploads each message to folder with name from "tag" in config file.
  - Append other labels using the *STORE* command in conjunction with the
    *+X-GM-LABELS* attribute (GMail IMAP extension).
